#!/usr/bin/env ruby
require 'github_flow_cli/cli'
begin
  GithubFlowCli::Config.setup unless ARGV == ["login"] || ARGV == ["help"] || ARGV.empty?
  GithubFlowCli::CLI.start
rescue Interrupt => e
  puts "\nbye."
ensure
  if GithubFlowCli::Config.valid?
    GithubFlowCli::Config.save!
  end
end
